### ISSUE TITLE
How to get second or third definitions

### ISSUE THREAD

**Issue by arnoldtonderaimarunda** [nitishparkar/dictionary-lookup-rb#1]
@nitishparkar  I am interested in using dictionary_lookup.  For example the word `green`. There are 3 definitions. Using `results.first.part_of_speech` and `results.first.denotation` give us the first definition. Could you please tell me how we would obtain the second or third definitions.

**Comment by arnoldtonderaimarunda** [comment]
Hi @nitishparkar - forgive me, I am still new to Ruby. Having put in a bit more research/thought I realised that you can manipulate the array using the methods:- `array.first` and  `array.shift` in a loop.

**Comment by nitishparkar** [comment]
@arnoldfungai `results` is just an `Array`. You could also use `results[0]`, `results[1]`, etc. or iterate over it using `each`, `map`.
