### ISSUE TITLE
Headword == Term, eliminating relevant entries of people and places

### ISSUE THREAD

**Issue by arnoldtonderaimarunda** [nitishparkar/dictionary-lookup-rb#2]
Hi @nitishparkar , got another issue to pick your brain :)

In `pearson.rb`, the line 36 `results = data["results"].select{ |d| d["headword"].downcase == term.downcase }` is useful in eliminating a lot of the less relevant entries.

However, it is eliminating some very relevant entries, especially of people and places. e.g **Barack Obama, Michael Jackson,**  or  **The Philippines**. 

This is because the Pearson API `headword`format for 
1. people is **Surname, Firstname**. Therefore, `obama, barack` will not equal lookup term `obama` 
2. some places is **Place, prefix**. Therefore,  `philippines, the` will not equal lookup term `philippines`

As a ruby newbie I don't know the best way to resolve this. My initial thoughts are to alter line 36 as follows; `
results = data["results"].select{ |d| dhead = d["headword"].downcase
        d["headword"].downcase == term.downcase or d["headword"].downcase[0,term.length+1] == term.downcase + ","
      }.
` This caters for above mentioned headword format as I noticed that Pearson place a `,` after such entries.

**Comment by arnoldtonderaimarunda** [comment]
A fork with the above-mentioned solution now available at https://github.com/arnoldfungai/PearsonLongman-Dictionary

**Comment by nitishparkar** [comment]
@arnoldfungai Thanks for pointing that out. I didn't have names of people and places in mind while building this.

However, just looking at the location of the comma may lead to some irregularities in the results. e.g try looking up `michael`

**Comment by arnoldtonderaimarunda** [comment]
@nitishparkar, updated the code above and forked gem to handle the irregularities in results as you mentioned. Thanks for highlighting it.
